name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace Firebase config
        run: |
          sed -i 's/"__FIREBASE_API_KEY__"/"${{ secrets.FIREBASE_API_KEY }}"/g' js/storage.js
          sed -i 's/"__FIREBASE_AUTH_DOMAIN__"/"${{ secrets.FIREBASE_AUTH_DOMAIN }}"/g' js/storage.js
          sed -i 's/"__FIREBASE_PROJECT_ID__"/"${{ secrets.FIREBASE_PROJECT_ID }}"/g' js/storage.js
          sed -i 's/"__FIREBASE_STORAGE_BUCKET__"/"${{ secrets.FIREBASE_STORAGE_BUCKET }}"/g' js/storage.js
          sed -i 's/"__FIREBASE_MESSAGING_SENDER_ID__"/"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"/g' js/storage.js
          sed -i 's/"__FIREBASE_APP_ID__"/"${{ secrets.FIREBASE_APP_ID }}"/g' js/storage.js
          sed -i 's/"__FIREBASE_DATABASE_URL__"/"${{ secrets.FIREBASE_DATABASE_URL }}"/g' js/storage.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .