name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace Firebase config
        run: |
          sed -i 's/process.env.FIREBASE_API_KEY/"${{ secrets.FIREBASE_API_KEY }}"/g' js/storage.js
          sed -i 's/process.env.FIREBASE_AUTH_DOMAIN/"${{ secrets.FIREBASE_AUTH_DOMAIN }}"/g' js/storage.js
          sed -i 's/process.env.FIREBASE_PROJECT_ID/"${{ secrets.FIREBASE_PROJECT_ID }}"/g' js/storage.js
          sed -i 's/process.env.FIREBASE_STORAGE_BUCKET/"${{ secrets.FIREBASE_STORAGE_BUCKET }}"/g' js/storage.js
          sed -i 's/process.env.FIREBASE_MESSAGING_SENDER_ID/"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"/g' js/storage.js
          sed -i 's/process.env.FIREBASE_APP_ID/"${{ secrets.FIREBASE_APP_ID }}"/g' js/storage.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .